package com.ex.exceptions;

public class UnderstandingException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

			System.out.println("at beginning of main");
		
			int[] arr = new int[4];
			arr[0]=1;
			arr[10] = 10;
		
			System.out.println("at the end of chain");
		
		
	}

}
